In [1]:
import numpy as np

In [3]:
# initializing arrays
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
# 2 dimensional
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])

In [6]:
b

array([[4., 5., 6.],
       [7., 8., 9.]])

In [7]:
# get dimension
a.ndim

1

In [8]:
# get shape
b.shape

(2, 3)

In [9]:
# get type, how much memory our array takes
a.dtype

dtype('int32')

In [10]:
# get size
b.itemsize

8

In [11]:
# get total size
a.size

3

### Accessing/Changing specific elements, rows, columns etc

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a.shape

(2, 7)

In [14]:
# get a specific element (r, c)
a[0, 5]

6

In [15]:
# get aspecific row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [16]:
# get specific column
a[:, 4]

array([ 5, 12])

In [17]:
# get fancy(startingindex:endindindex:stepsize)
a[1, 1:6:2]

array([ 9, 11, 13])

In [18]:
# replace an element
a[1,5] =26
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 26 14]]


#### 3d example

In [19]:
c = np.array([[4,3,8],[12,2,1],[5,9,11]])
c

array([[ 4,  3,  8],
       [12,  2,  1],
       [ 5,  9, 11]])

In [20]:
c.shape

(3, 3)

In [21]:
c.itemsize

4

In [22]:
c.dtype

dtype('int32')

## initializing different types of arrays

In [23]:
# all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# all 1s matrix
np.ones((3,4,))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# any other number
np.full((3,3), 26)

array([[26, 26, 26],
       [26, 26, 26],
       [26, 26, 26]])

In [28]:
# any other shape(full_like)
np.full_like(a,7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [30]:
# random decimal numbers
np.random.rand(4,2,3)

array([[[0.14535128, 0.55211094, 0.35477815],
        [0.88497459, 0.42857853, 0.33684488]],

       [[0.4327818 , 0.68618099, 0.27165318],
        [0.78442351, 0.76676356, 0.98721037]],

       [[0.91930445, 0.06955315, 0.20438331],
        [0.09748078, 0.47090509, 0.77864328]],

       [[0.77940501, 0.39274226, 0.90320122],
        [0.24123754, 0.14601118, 0.99415216]]])

In [31]:
# random integer
np.random.randint(6, size = (3,3))

array([[2, 1, 3],
       [1, 2, 3],
       [4, 0, 0]])

In [31]:
# the identity matrix (The identity array is a square array with ones on the main diagonal)
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
# repeat an array
d = np.array([[4,5,6]])
r1 = np.repeat(d,3, axis=0)
print(r1)

[[4 5 6]
 [4 5 6]
 [4 5 6]]


In [33]:
# excercise
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1,1:-1] = z
print(output)# 33:58

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [33]:
import numpy as np
a = np.array([2,5,8])
b = a.copy()
b[0] = 57
print(b)

[57  5  8]


### Mathematics

In [10]:
d = np.array([9,8,7,6])
print(d)

[9 8 7 6]


In [11]:
d + 2

array([11, 10,  9,  8])

In [12]:
d - 2

array([7, 6, 5, 4])

In [13]:
d * 2

array([18, 16, 14, 12])

In [14]:
d / 2

array([4.5, 4. , 3.5, 3. ])

In [16]:
e = np.array([5,4,3,2])

In [17]:
d + e

array([14, 12, 10,  8])

In [18]:
d ** 2

array([81, 64, 49, 36], dtype=int32)

In [19]:
e ** 2

array([25, 16,  9,  4], dtype=int32)

In [20]:
# take the sin
np.sin(d)

array([ 0.41211849,  0.98935825,  0.6569866 , -0.2794155 ])

In [21]:
# more on (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

#### Linear Algebra

In [24]:
f = np.ones((2,3))
print(f)

g = np.full((3,2), 2)
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [25]:
np.matmul(f,g)

array([[6., 6.],
       [6., 6.]])

In [34]:
# find the determinant
c = np.identity(6)
np.linalg.det(c)

1.0

#### Statistics

In [36]:
stats = np.array([[2,5,8],[3,6,9]])
stats

array([[2, 5, 8],
       [3, 6, 9]])

In [37]:
np.min(stats)

2

In [38]:
np.max(stats)

9

In [39]:
np.sum(stats)

33

### Reorganizing arrays

In [43]:
before = np.array([[1,4,7,2], [5,8,3,6]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 4 7 2]
 [5 8 3 6]]
[[1 4]
 [7 2]
 [5 8]
 [3 6]]


In [46]:
# vertically stacking metrices
b = np.array([2,4,6,8])
b1 = np.array([3,6,9,12])

np.vstack([b,b1,b,b1])

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [49]:
# horizontal stack
c = np.ones((2,4))
c1 = np.zeros((2,2))

np.hstack([c,c1])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscelleneous
#### Load data from file

In [35]:
import numpy as np
file_data = np.genfromtxt('Rand.txt', delimiter =',')
file_data = file_data.astype('int32')
print(file_data)

[[  1  13  21  11 196  75   4   3  34]
 [  3  42  12   3 766   4  55   6  11]
 [  1  22  33  11 999  13   2   1   0]]


### Boolean masking and advanced indexing

In [36]:
file_data > 50

array([[False, False, False, False,  True,  True, False, False, False],
       [False, False, False, False,  True, False,  True, False, False],
       [False, False, False, False,  True, False, False, False, False]])

In [14]:
# index
file_data[file_data > 50]

array([196,  75, 766,  55, 999])

In [15]:
# you can index with a list in numpy
q = np.array([1,2,3,5,9,8,7,4,6])
q[[1,2,8]]

array([2, 3, 6])

In [38]:
np.any(file_data > 50, axis=0)

array([False, False, False, False,  True,  True,  True, False, False])

In [19]:
np.all(file_data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False])

In [23]:
((file_data > 50)&(file_data < 100))

array([[False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [24]:
# not ~
(~((file_data > 50)&(file_data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])